### ISSUE TITLE
Multiple Artists - works ok, but

### ISSUE THREAD

**Issue by rpneid** [jbyall/looking2#23]
the word "and" should be either automatically inserted to join the names of the artist, or the form should be edited to include this in the instruction.

"at [venue]" shows up in the top line perfectly - it is automatically inserted

however, the venue is not searchable in description - useful if i wanted to find all the shows at Spirit Hall (an acceptable use by a Looker)

see: Waxahatchee and Ought at Spirit Hall for reference

**Comment by jbyall** [comment]
There are 2 separate issues and have been moved to issue #27 and issue #26
